### ISSUE TITLE
Make the initial config interactive, GUI based :)

### ISSUE THREAD

**Issue by mohilkhare1708** [Deep-Codes/Birthday-Wisher#2]
Instead of making users edit the Birthday.jsx file, we can make a form to make that process easy to eye and interactive. :)

P.S. The about section needs to change. :P

**Comment by Deep-Codes** [comment]
@mohilkhare1708 Hey! About having a **GIU FORM** instead of going into `Birthday.jsx` file it is implemented just for 1 person because it has a birthday🎂  wishing part too along with countdown📆  and the repo `Birthday-Wisher` main aim is for that purpose. 

Coming to the **About Section** which part exactly? I would be happy to Fix it .

Thanks for the Issue !

**Comment by Deep-Codes** [comment]
@mohilkhare1708 I will implement the **GUI Form** in this with a different Route.

**Comment by mohilkhare1708** [comment]
> @mohilkhare1708 Hey! About having a **GIU FORM** instead of going into `Birthday.jsx` file it is implemented just for 1 person because it has a birthday🎂 wishing part too along with countdown📆 and the repo `Birthday-Wisher` main aim is for that purpose.
> 
> Coming to the **About Section** which part exactly? I would be happy to Fix it .
> 
> Thanks for the Issue !

For People for are bad at Wishing Birthdays - ReactJS >> For People who are bad at Wishing Birthdays

just a minor typo there lol
